# Site settings
title: The Vampire
email: bionicle.dragon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my entry for Ludum Dare 33 --- *You Are the Monster*.
baseurl: "/LD33" # the subpath of your site, e.g. /blog/
url: "http://calebjones.net" # the base hostname & protocol for your site
twitter_username: porglezomp
github_username:  porglezomp

# Build settings
markdown: kramdown
